### ISSUE TITLE
Could not find 'viz/common 

### ISSUE THREAD

**Issue by yohannes-taye** [shubham-goel/ds#2]
Thank you for the great work. I cloned the repo and tried to run the given examples but Im getting the error below. What do you think might be causing the problem? 
```

Traceback (most recent call last):
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tmc/projects/ds/src/exp/ds.py", line 1285, in <module>
    main()
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 88, in run
    cfg = self.compose_config(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 559, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 239, in _load_configuration_impl
    defaults_list = create_defaults_list(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 747, in create_defaults_list
    defaults, tree = _create_defaults_list(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 717, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 355, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 454, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 574, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 517, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 574, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 517, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 574, in _create_defaults_tree_impl
    add_child(children, new_root)
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 517, in add_child
    subtree_ = _create_defaults_tree_impl(
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 485, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/home/tmc/miniconda3/envs/ds/lib/python3.8/site-packages/hydra/_internal/defaults_list.py", line 801, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'base': Could not find 'viz/common'

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/tmc/projects/ds/configs
        provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
        provider=schema, path=structured://
```

**Comment by shubham-goel** [comment]
Whoops! I forgot to add a config file to the commit. Thanks for pointing it out, let me fix this.
